call SDL_Quit() on exit to prevent a crash on app exit with linux/wayland
LIJI32/SameBoy pull request #631
Opened 2024-06-02 18:32 UTC by laamaa

On Bluefin DX Linux (a Fedora Silverblue spinoff) closing the app window brings down the whole Gnome session. Ensuring that SDL_Quit() (https://wiki.libsdl.org/SDL2/SDL_Quit) is called on exit seems to prevent this

2024-06-14 21:21 UTC, ISSOtm requested changes
This works for me under Linux+Wayland (sway), but so does `master` FWIW. `sway` does not log any errors.

I suggest you also report a bug to the GNOME developers&mdash;I do not think that the *entire session* should be *able* to be brought down by a single misbehaving program.

Though this workaround is still worth merging, IMO. Albeit I made some context-adding suggestions, subject to your convenience.

2024-06-14 21:21 UTC, ISSOtm commented on SDL/main.c
> +    atexit(SDL_Quit);
```suggestion
    // This is, essentially, best-effort.
    // This function will not be called if the process is terminated in any way, anyhow.
    (void)atexit(SDL_Quit);
```

2024-06-15 17:38 UTC, laamaa commented
Good idea, I added the suggestions to the commit. The issue doesn't seem to happen on vanilla Silverblue/Gnome (without proprietary NVIDIA drivers installed, unlike Bluefin), but I remember bumping into the same problem at some point in my own SDL based project, so it's probably a good idea to have it there just in case...

2024-06-18 11:16 UTC, ISSOtm approved these changes
Seems fair to me, then :)

2024-06-19 17:02 UTC, merged